from typing import Dict

from resources.lib.model.inputdevice import InputDevice
from resources.lib.repository.inputrepository import InputRepository


class InputManager:
    repository = ... # type: InputRepository
    def __init__(self, repository: InputRepository): ...
    def get_input_devices(self) -> Dict[InputDevice]: ...
    def add_input_device(self, device_id: str, device: InputDevice) -> None: ...
    def remove_input_device(self, device_id: str) -> None: ...
    def update_input_device(self, device_id: str, device: InputDevice) -> None: ...
