# Stubs for discoveryagent (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List, AnyStr
from zeroconf import ServiceBrowser, ServiceStateChange, Zeroconf

from resources.lib.model.mdnscomputer import MdnsComputer


class DiscoveryAgent:
    service_type = ... # type: Any
    available_hosts = ... # type: List[MdnsComputer]
    zeroconf = ... # type: Zeroconf
    browser = ... # type: ServiceBrowser
    def __init__(self): ...
    def service_state_change(self, zeroconf:Zeroconf, service_type:AnyStr, name:AnyStr, state_change:ServiceStateChange): ...
    def start_discovery(self, timeout=3) -> List[MdnsComputer]: ...
