# Stubs for hostrepository (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Dict
from xbmcswift2 import TimedStorage

from resources.lib.core.corefunctions import Core
from resources.lib.core.logger import Logger
from resources.lib.model.hostdetails import HostDetails


class HostRepository:
    storage = ... # type: TimedStorage
    logger = ... # type: Logger
    def __init__(self, core:Core): ...
    def get_hosts(self) -> Dict[HostDetails]: ...
    def add_host(self, host:HostDetails, flush=True): ...
    def remove_host(self, host:HostDetails, flush=True): ...
    def remove_host_by_id(self, host_id, flush=True): ...
    def get_host_by_id(self, host_id) -> HostDetails: ...
