class Fanart:
    original = ... # type: str
    thumb = ... # type: str
    def __init__(self, original:str=None, thumb:str=None): ...
    def get_original(self) -> str: ...
    def set_original(self, original:str): ...
    def get_thumb(self) -> str: ...
    def set_thumb(self, thumb:str): ...
