# Stubs for mdnscomputer (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import AnyStr
from zeroconf import ServiceInfo


class MdnsComputer:
    service_type = ... # type: AnyStr
    name = ... # type: AnyStr
    address = ... # type: AnyStr
    port = ... # type: AnyStr
    server = ... # type: AnyStr
    def __init__(self, service_type:AnyStr, name:AnyStr, address:AnyStr, port:AnyStr, server:AnyStr): ...
    @classmethod
    def from_service_info(cls, service_info: ServiceInfo): ...
