# Stubs for gamelist (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import List

import xbmcgui
from resources.lib.core.logger import Logger
from resources.lib.manager.gamemanager import GameManager
from resources.lib.model.game import Game
from resources.lib.model.hostdetails import HostDetails
from resources.lib.util.gamehelper import GameController
from resources.lib.views.gamelist import GameList as GameListType
from xbmcgui import Action, ControlImage, ControlList


class GameList(xbmcgui.WindowXML):
    def __new__(cls:GameListType, *args, **kwargs): ...
    host = ... # type: HostDetails
    games = ... # type: List(Game)
    game_manager = ... # type: GameManager
    game_controller = ... # type: GameController
    logger = ... # type: Logger
    list = ... # type: ControlList
    cover = ... # type: ControlImage
    fanart = ... # type: ControlImage
    def __init__(self:GameListType, host:HostDetails): ...
    def onInit(self): ...
    def build_list(self): ...
    def onAction(self, action:Action): ...
    def update(self): ...
