# Stubs for gamelist (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from typing import List

from resources.lib.manager.gamemanager import GameManager
from resources.lib.model.game import Game
from resources.lib.model.hostdetails import HostDetails
from resources.lib.views.gamelist import GameList as GameListType
from xbmcgui import Action, ControlImage, ControlList


class GameList(xbmcgui.WindowXML):
    def __new__(cls:GameListType, *args, **kwargs): ...
    host = ... # type: HostDetails
    games = ... # type: List(Game)
    game_manager = ... # type: GameManager
    list = ... # type: ControlList
    cover = ... # type: ControlImage
    fanart = ... # type: ControlImage
    def __init__(self:GameListType, host:HostDetails, games:List(Game)): ...
    def onInit(self): ...
    def buildList(self): ...
    def onAction(self, action:Action): ...
