# Stubs for audiocontroller (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
from xbmcswift2 import Plugin

from resources.lib.util.audiomanager import AudioManager
from resources.lib.util.confighelper import ConfigHelper


class AudioController:
    audio_manager = ... # type: AudioManager
    config_helper = ... # type: ConfigHelper
    def __init__(self, audio_manager: AudioManager, config_helper: ConfigHelper, plugin: Plugin): ...
    def select_audio_device(self) -> None: ...
