# Stubs for hostmanager (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Dict, AnyStr

from resources.lib.core.corefunctions import Core
from resources.lib.core.logger import Logger
from resources.lib.manager.hostmanager import HostManager
from resources.lib.model.hostdetails import HostDetails
from resources.lib.model.mdnscomputer import MdnsComputer
from resources.lib.nvhttp.connectionmanager.connectionmanager import ConnectionManager
from resources.lib.nvhttp.mdns.discoveryagent import DiscoveryAgent


class HostController:
    discovery_agent = ... # type: DiscoveryAgent
    def __init__(self, logger:Logger, core:Core, connection_manager:ConnectionManager, host_manager:HostManager):
        self.logger = Logger
        self.core = Core
        self.connection_manager = ConnectionManager
        self.host_manager = HostManager
        ...
    def initiate(self): ...
    def pair_selected_host(self, host:HostDetails): ...
    def select_host(self, hosts: Dict[MdnsComputer]): ...
    def enter_ip(self) -> AnyStr: ...
    def __load_agent(self): ...
