# Stubs for corefunctions (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
from typing import AnyStr
from xbmcswift2 import Plugin, TimedStorage

from resources.lib.core.logger import Logger

internal_path = ... # type: str
STRINGS = ... # type: dict

class Core:
    plugin = ... # type: Plugin
    logger = ... # type: Logger
    storage_path = ... # type: AnyStr
    def __init__(self, plugin: Plugin, logger: Logger) -> None: ...
    def string(self, string_id: str) -> str: ...
    def check_script_permissions(self) -> None: ...
    def get_storage(self, name='game_storage', file_format='pickle', TTL=None) -> TimedStorage: ...
    def get_active_skin(self) -> str: ...
