# Stubs for corefunctions (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from xbmcswift2 import Plugin, TimedStorage

from resources.lib.core.logger import Logger

internal_path = ... # type: str
STRINGS = ... # type: dict

class Core:
    plugin = ... # type: Plugin
    logger = ... # type: Logger
    def __init__(self, plugin: Plugin, logger: Logger): ...
    def string(self, string_id): ...
    def check_script_permissions(self): ...
    def get_storage(self) -> TimedStorage: ...
    def get_active_skin(self): ...
