# Stubs for corefunctions (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
from typing import AnyStr
from xbmcaddon import Addon

from resources.lib.core.logger import Logger
from resources.lib.storageengine.storage import TimedStorage

internal_path = ... # type: str
STRINGS = ... # type: dict

class Core:
    addon = ... # type: Addon
    logger = ... # type: Logger
    storage_path = ... # type: AnyStr
    def __init__(self, addon: Addon, logger: Logger) -> None: ...
    def string(self, string_id: str) -> str: ...
    def check_script_permissions(self) -> None: ...
    def get_storage(self, name='game_storage', file_format='pickle', TTL=None) -> TimedStorage: ...
    def get_active_skin(self) -> str: ...
