# Stubs for updateservice (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Union
from xbmcswift2 import Plugin

from resources.lib.core.corefunctions import Core
from resources.lib.core.logger import Logger
from resources.lib.model.update import Update


class UpdateService:
    regexp = ... # type: str
    api_url = ... # type: str
    pre_api_url = ... # type: str
    plugin = ... # type: Plugin
    core = ... # type: Core
    logger = ... # type: Logger
    current_version = ... # type: str
    update_version = ... # type: str
    asset_url = ... # type: str
    asset_name = ... # type: str
    changelog = ... # type: str
    def __init__(self, plugin: Plugin, core: Core, logger: Logger): ...
    def check_for_update(self, ignore_checked:bool) -> Union(Update, None): ...
    def initiate_update(self, update: Update) -> None: ...
    def do_update(self, update: Update) -> None: ...
