# Stubs for audiomanager (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List
from resources.lib.model.audiodevice import AudioDevice


class AudioManager:
    CARDS_REGEX = ... # type: str
    devices = ... # type: List[AudioDevice]
    def __init__(self): ...
    def init_devices(self) -> None: ...
    def get_card_info(self, idx: str, audio_id: str, audio_name: str) -> List[AudioDevice]: ...
    def get_device_by_name(self, name: str) -> AudioDevice: ...
