# Stubs for moonlighthelper (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List

from resources.lib.core.corefunctions import Core
from resources.lib.core.logger import Logger
from resources.lib.model.inputdevice import InputDevice
from resources.lib.model.nvapp import NvApp
from resources.lib.nvhttp.request.requestservice import RequestService
from resources.lib.service.hostcontextservice import HostContextService
from resources.lib.util.confighelper import ConfigHelper
from xbmcgui import DialogProgress


def loop_lines(dialog, iterator): ...

class MoonlightHelper:
    regex_connect = ... # type: str
    regex_moonlight = ... # type: str
    regex_certificate_gen = ... # type: str
    regex_connection_failed = ... # type: str
    core = ... # type: Core
    config_helper = ... # type: ConfigHelper
    host_context_service = ... # type: HostContextService
    request_service = ... # type: RequestService
    logger = ... # type: Logger
    internal_path = ... # type: str
    def __init__(self, core: Core, config_helper: ConfigHelper, host_context_service: HostContextService, request_service: RequestService, logger: Logger) -> None: ...
    def create_ctrl_map(self, dialog: DialogProgress, map_file: str) -> bool: ...
    def create_ctrl_map_new(self, dialog: DialogProgress, map_file: str, device: InputDevice) -> bool: ...
    def pair_host(self, dialog: DialogProgress) -> (str, str): ...
    def launch_game(self, game_id: str) -> None: ...
    def list_games(self) -> List[NvApp]: ...
