# Stubs for moonlighthelper (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
from xml.etree.ElementTree import ElementTree

from typing import Dict
from typing import List

from resources.lib.core.logger import Logger
from resources.lib.model.settings.category import Category
from xbmcaddon import Addon


class SettingsParser:
    settings_path = ... # type: str
    settings_tree = ... # type: ElementTree
    settings_hash = ... # type: str
    logger = ... # type: Logger
    settings_dict = ... # type: Dict
    addon = ... # type: Addon
    def __init__(self, addon: Addon, logger: Logger) -> None: ...
    def _get_settings_hash(self) -> str: ...
    def _reload_settings(self) -> None: ...
    def get_settings(self) -> Dict[Category]: ...
